import type { Store, Product, Order, Category } from './types'

export const CATEGORIES: Category[] = [
  { id: '1', name: { kk: 'Барлығы', ru: 'Все', en: 'All' }, icon: '🍽️', slug: 'all' },
  { id: '2', name: { kk: 'Роллдар', ru: 'Суши & Роллы', en: 'Sushi & Rolls' }, icon: '🍱', slug: 'sushi' },
  { id: '3', name: { kk: 'Бургерлер', ru: 'Бургеры', en: 'Burgers' }, icon: '🍔', slug: 'burgers' },
  { id: '4', name: { kk: 'Пицца', ru: 'Пицца', en: 'Pizza' }, icon: '🍕', slug: 'pizza' },
  { id: '5', name: { kk: 'Азиат тағамы', ru: 'Азиатская кухня', en: 'Asian' }, icon: '🥢', slug: 'asian' },
  { id: '6', name: { kk: 'Азық-түлік', ru: 'Продукты', en: 'Grocery' }, icon: '🛒', slug: 'grocery' },
  { id: '7', name: { kk: 'Кофехана', ru: 'Кофейня', en: 'Coffee' }, icon: '☕', slug: 'coffee' },
  { id: '8', name: { kk: 'Десерттер', ru: 'Десерты', en: 'Desserts' }, icon: '🍰', slug: 'desserts' },
]

export const STORES: Store[] = [
  {
    id: '1',
    name: 'Sakura Sushi',
    description: {
      kk: 'Дәстүрлі жапон тағамдары',
      ru: 'Традиционная японская кухня',
      en: 'Traditional Japanese cuisine',
    },
    category: 'sushi',
    logo: '🍣',
    coverImage: '',
    rating: 4.8,
    reviewCount: 234,
    deliveryTime: 30,
    deliveryFee: 300,
    minOrder: 2000,
    isOpen: true,
    address: 'Алматы, Абай д. 15',
    phone: '+7 777 111 22 33',
  },
  {
    id: '2',
    name: 'Burger House',
    description: {
      kk: 'Сочный гамбургерлер',
      ru: 'Сочные гамбургеры',
      en: 'Juicy burgers',
    },
    category: 'burgers',
    logo: '🍔',
    coverImage: '',
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: 25,
    deliveryFee: 250,
    minOrder: 1500,
    isOpen: true,
    address: 'Алматы, Сейфуллин д. 20',
    phone: '+7 777 222 33 44',
  },
  {
    id: '3',
    name: 'Pizza Palace',
    description: {
      kk: 'Итальян пиццасы',
      ru: 'Итальянская пицца',
      en: 'Italian pizza',
    },
    category: 'pizza',
    logo: '🍕',
    coverImage: '',
    rating: 4.7,
    reviewCount: 312,
    deliveryTime: 35,
    deliveryFee: 200,
    minOrder: 2500,
    isOpen: true,
    address: 'Алматы, Назарбаев д. 100',
    phone: '+7 777 333 44 55',
  },
  {
    id: '4',
    name: 'Wok & Go',
    description: {
      kk: 'Азиат вок тағамдары',
      ru: 'Азиатские блюда вок',
      en: 'Asian wok dishes',
    },
    category: 'asian',
    logo: '🥢',
    coverImage: '',
    rating: 4.5,
    reviewCount: 156,
    deliveryTime: 20,
    deliveryFee: 0,
    minOrder: 1800,
    isOpen: false,
    address: 'Алматы, Достык д. 55',
    phone: '+7 777 444 55 66',
  },
  {
    id: '5',
    name: 'Green Mart',
    description: {
      kk: 'Жаңа азық-түліктер',
      ru: 'Свежие продукты',
      en: 'Fresh groceries',
    },
    category: 'grocery',
    logo: '🛒',
    coverImage: '',
    rating: 4.4,
    reviewCount: 421,
    deliveryTime: 45,
    deliveryFee: 400,
    minOrder: 3000,
    isOpen: true,
    address: 'Алматы, Розыбакиев д. 8',
    phone: '+7 777 555 66 77',
  },
  {
    id: '6',
    name: 'Brew & Beans',
    description: {
      kk: 'Сапалы кофе мен тәттілер',
      ru: 'Качественный кофе и выпечка',
      en: 'Quality coffee and pastries',
    },
    category: 'coffee',
    logo: '☕',
    coverImage: '',
    rating: 4.9,
    reviewCount: 567,
    deliveryTime: 20,
    deliveryFee: 150,
    minOrder: 800,
    isOpen: true,
    address: 'Алматы, Панфилова д. 90',
    phone: '+7 777 666 77 88',
  },
]

export const PRODUCTS: Product[] = [
  // Sakura Sushi
  {
    id: 'p1', storeId: '1',
    name: { kk: 'Филадельфия', ru: 'Филадельфия', en: 'Philadelphia' },
    description: { kk: 'Лосось, кілегей ірімшік, авокадо', ru: 'Лосось, сливочный сыр, авокадо', en: 'Salmon, cream cheese, avocado' },
    price: 2900, originalPrice: 3200,
    category: 'rolls', isAvailable: true, isPopular: true, isNew: false,
  },
  {
    id: 'p2', storeId: '1',
    name: { kk: 'Калифорния', ru: 'Калифорния', en: 'California' },
    description: { kk: 'Краб, авокадо, қияр', ru: 'Краб, авокадо, огурец', en: 'Crab, avocado, cucumber' },
    price: 2600,
    category: 'rolls', isAvailable: true, isPopular: false, isNew: false,
  },
  {
    id: 'p3', storeId: '1',
    name: { kk: 'Дракон', ru: 'Дракон', en: 'Dragon Roll' },
    description: { kk: 'Тунец, авокадо, жапондық сос', ru: 'Тунец, авокадо, японский соус', en: 'Tuna, avocado, Japanese sauce' },
    price: 3200,
    category: 'rolls', isAvailable: true, isPopular: true, isNew: true,
  },
  {
    id: 'p4', storeId: '1',
    name: { kk: 'Мисо сорпасы', ru: 'Мисо-суп', en: 'Miso Soup' },
    description: { kk: 'Тофу, вакаме, жасыл пияз', ru: 'Тофу, вакаме, зелёный лук', en: 'Tofu, wakame, green onion' },
    price: 800,
    category: 'soups', isAvailable: true, isPopular: false, isNew: false,
  },
  // Burger House
  {
    id: 'p5', storeId: '2',
    name: { kk: 'Классик', ru: 'Классик', en: 'Classic Burger' },
    description: { kk: 'Сиыр еті, салат, кетчуп', ru: 'Говядина, салат, кетчуп', en: 'Beef, lettuce, ketchup' },
    price: 1800,
    category: 'burgers', isAvailable: true, isPopular: true, isNew: false,
  },
  {
    id: 'p6', storeId: '2',
    name: { kk: 'Чикен Бургер', ru: 'Чикен Бургер', en: 'Chicken Burger' },
    description: { kk: 'Тауық, майонез, тұздықталған қияр', ru: 'Курица, майонез, маринованный огурец', en: 'Chicken, mayo, pickles' },
    price: 1600,
    category: 'burgers', isAvailable: true, isPopular: false, isNew: true,
  },
  {
    id: 'p7', storeId: '2',
    name: { kk: 'Картоп фри', ru: 'Картофель фри', en: 'French Fries' },
    description: { kk: 'Алтын-сары, хрустящий', ru: 'Золотистый, хрустящий', en: 'Golden and crispy' },
    price: 600,
    category: 'sides', isAvailable: true, isPopular: false, isNew: false,
  },
  // Pizza Palace
  {
    id: 'p8', storeId: '3',
    name: { kk: 'Маргарита', ru: 'Маргарита', en: 'Margherita' },
    description: { kk: 'Помидор, моцарелла', ru: 'Томат, моцарелла', en: 'Tomato, mozzarella' },
    price: 2400,
    category: 'pizza', isAvailable: true, isPopular: false, isNew: false,
  },
  {
    id: 'p9', storeId: '3',
    name: { kk: 'Пепперони', ru: 'Пепперони', en: 'Pepperoni' },
    description: { kk: 'Пепперони, моцарелла, итальян шөп', ru: 'Пепперони, моцарелла, итальянские травы', en: 'Pepperoni, mozzarella, herbs' },
    price: 2700,
    category: 'pizza', isAvailable: true, isPopular: true, isNew: false,
  },
  // Wok & Go
  {
    id: 'p10', storeId: '4',
    name: { kk: 'Тауықты Вок', ru: 'Вок с курицей', en: 'Chicken Wok' },
    description: { kk: 'Тауық, нудл, азиаттық сос', ru: 'Курица, лапша, азиатский соус', en: 'Chicken, noodles, Asian sauce' },
    price: 2100,
    category: 'wok', isAvailable: true, isPopular: true, isNew: false,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord1',
    customerId: 'user1',
    customerName: 'Айгерим Назарова',
    storeId: '1',
    storeName: 'Sakura Sushi',
    courierId: 'c1',
    courierName: 'Дамир К.',
    items: [
      { productId: 'p1', productName: 'Филадельфия', price: 2900, quantity: 2 },
      { productId: 'p4', productName: 'Мисо-суп', price: 800, quantity: 1 },
    ],
    status: 'delivering',
    subtotal: 6600,
    deliveryFee: 300,
    total: 6900,
    address: 'Алматы, ул. Абай 15, кв. 45',
    phone: '+7 777 123 45 67',
    paymentMethod: 'card',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'ord2',
    customerId: 'user1',
    customerName: 'Айгерим Назарова',
    storeId: '2',
    storeName: 'Burger House',
    items: [
      { productId: 'p5', productName: 'Классик', price: 1800, quantity: 1 },
      { productId: 'p7', productName: 'Картофель фри', price: 600, quantity: 2 },
    ],
    status: 'delivered',
    subtotal: 3000,
    deliveryFee: 250,
    total: 3250,
    address: 'Алматы, ул. Абай 15, кв. 45',
    phone: '+7 777 123 45 67',
    paymentMethod: 'cash',
    createdAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 3600000 + 3600000).toISOString(),
  },
]
